---
- name: copy logging config files
  copy:
    src: files/{{ path }}/
    dest: /{{ path }}
    owner: root
    group: root
    mode: u=rw,go=r
  loop:
    - etc/logrotate.d
    - etc/rsyslog.d
  loop_control:
    loop_var: path

- name: create svc group
  group:
    name: svc
    state: present

- name: copy app files
  copy:
    src: files/opt/app/
    dest: /opt/app
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: Change file ownership, group and permissions
  file:
    path: /opt/app/bin/ctl.sh
    mode: '755'

- name: create symbolic link
  file:
    src: /opt/app/bin/ctl.sh
    dest: /usr/bin/appctl
    state: link

- name: set up dev env
  copy:
    dest: /opt/app/bin/envs/appdev.env
    content: |
      APPCTL_ENV=dev

  when: target_env == 'dev'

- name: copy limits file
  copy:
    src: files/etc/security/limits.d/limits.conf
    dest: /etc/security/limits.d/limits.conf
    owner: root
    group: svc
    mode: preserve

- name: set defualt limit for user
  shell: sed -i 's/#DefaultLimitNOFILE=/DefaultLimitNOFILE=65535/g' /etc/systemd/user.conf

- name: set defualt limit for system
  shell: sed -i 's/#DefaultLimitNOFILE=/DefaultLimitNOFILE=65535/g' /etc/systemd/system.conf