---
- name: add the service group
  group:
    name: kafka
    state: present

- name: add the service user
  user:
    name: kafka
    groups: kafka
    shell: /sbin/nologin
    create_home: no
    home: "/opt/kafka/current"
    append: yes
    comment: "Service User"
    state: present

- name: install tools
  apt:
    update_cache: yes
    name: ['openjdk-8-jdk', 'unzip']
    state: present

- name: copy app files
  copy:
    src: files/opt/app/
    dest: /opt/app
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: create symbolic link for ctl.sh
  vars:
    src_file: /opt/app/bin/ctl.sh
  file:
    src: "{{ src_file }}"
    dest: /usr/bin/appctl
    state: link

- name: install confd files
  include_tasks: ../../utils/tasks/process-confd-files.yml

