appAgentVersion: v1.0.7
arping_version: "20211215-1"
kafka_version: "3.9.1"
scala_version: '2.13'
openjdk_version: "21.0.2"
kafka_manager_version: "3.0.0.6"
zabbix_version: "7.2"
caddy_version: v2.8.4
jmx_exporter_version: "1.4.0"
tar_version: "1.32-4"
kafka_ui_version: "v1.3.0"