---
- name: setvariables
  set_fact:
    kafka_manager_version: "{{ kafka_manager_version | d('3.0.0.6') }}"
    installPath: "/opt/kafka-manager"

- name: install confd files
  include_role:
    name: confd-files

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - kafka-manager
  loop_control:
    loop_var: svc_name

- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: prepare dir
  file:
    path: "{{ installPath }}/{{ kafka_manager_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ installPath }}/{{ kafka_manager_version }}"
    dest: "{{ installPath }}/current"
    state: link

# note: Cmak 3.0.0.0及以上版本需要Zookeeper3.5及其以上版本支持
# 现注释Cmak包编译安装部分，直接使用bin包


# - name: install manager 
#   include_role:
#     name: install
#   vars:
#     opts:
#       pkg_name: "kafka-manager"
#       pkg_version: "{{ kafka_manager_version }}"
#       pkg_type: zip
#       pkg_url: "https://github.com/yahoo/CMAK/archive/{{ kafka_manager_version }}.zip"
#       extracts: yes
#       dest_path: "~/.ansible/cache/kafka-manager/"
#       creates: "~/.ansible/cache/kafka-manager/kafka-manager-{{ kafka_manager_version }}/sbt"
#       bin_path:


# - name: build kafka manager
#   shell: ./sbt dist
#   args:
#     chdir: "~/.ansible/cache/kafka-manager/CMAK-{{ kafka_manager_version }}/"
#     executable: /bin/bash
#   delegate_to: localhost

# - name: copy bulit manager
#   copy:
#     src: ~/.ansible/cache/kafka-manager/CMAK-{{ kafka_manager_version }}/target/universal/cmak-{{ kafka_manager_version }}.zip
#     dest: /tmp/kafka-manager-{{ kafka_manager_version }}.zip
#     owner: kafka
#     group: kafka
#     mode: preserve
#     directory_mode: u=rwx,g=rx,o=

- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: cmak
      pkg_version: "{{ kafka_manager_version }}"
      pkg_feature: "linux"
      pkg_fileType: ".zip"
      pkg_url: "https://github.com/yahoo/CMAK/releases/download/{{ kafka_manager_version }}/cmak-{{ kafka_manager_version }}.zip"

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "/tmp"
    creates: "/tmp/cmak-{{ kafka_manager_version }}/bin/cmak"

- name: copy cmak files
  copy:
      src: /tmp/cmak-{{ kafka_manager_version }}/
      dest: "{{ installPath }}/current/"
      remote_src: yes

- name: link kafka-manager to cmak
  file:
    src: "{{ installPath }}/current/bin/cmak"
    dest: "{{ installPath }}/current/bin/kafka-manager"
    state: link

- name: Remove tmp files
  file:
    path: /tmp/cmak-{{ kafka_manager_version }}
    state: absent

- name: update permissions of service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    recurse: yes
    state: directory
  with_items:
    - kafka-manager

- name: setup journald.conf
  lineinfile:
    path: /etc/systemd/journald.conf
    line: 'ForwardToSyslog=no'
    state: present