---
- name: setvariables
  set_fact:
    kafka_manager_version: 3.0.0.4 #latest
    scala_version: "2.11"

- name: install confd files
  include_role:
    name: confd-files-1.0.2

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - cmak
  loop_control:
    loop_var: svc_name

- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: prepare service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    state: directory
  with_items:
    - cmak/cmak-{{ kafka_manager_version }}

- name: create symbolic links
  file:
    src: /opt/{{ item.name }}/{{ item.name }}-{{ item.version }}
    dest: /opt/{{ item.name }}/current
    owner: kafka
    group: kafka
    state: link
  with_items:
    - name: cmak
      version: "{{ kafka_manager_version }}"

- name: download kafka manager src
  get_url:
    url: https://github.com/yahoo/CMAK/releases/download/{{ item }}/cmak-{{ item }}.zip
    dest: /tmp/cmak-{{ item }}.zip
  with_items: "{{ kafka_manager_version }}"

- name: install kafka manager binaries
  unarchive:
    src: /tmp/cmak-{{ kafka_manager_version }}.zip
    dest: /opt/cmak
    owner: kafka
    group: kafka
    creates: /opt/cmak/cmak-{{ kafka_manager_version }}/bin/cmak
    remote_src: yes

- name: update permissions of service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    recurse: yes
    state: directory
  with_items:
    - cmak

