---
- name: setvariables
  set_fact:
    kafka_manager_version: "3.0.0.5"
    scala_version: "2.11"

- name: install java11
  apt:
    name: openjdk-11-jdk
    state: present

- name: install confd files
  include_role:
    name: confd-files

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - kafka-manager
  loop_control:
    loop_var: svc_name

- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: prepare service directories
  file:
    path: /opt/kafka-manager/{{ kafka_manager_version }}
    owner: kafka
    group: kafka
    state: directory

- name: create symbolic links
  file:
    src: /opt/{{ item.name }}/{{ item.version }}
    dest: /opt/{{ item.name }}/current
    owner: kafka
    group: kafka
    state: link
  with_items:
    - name: kafka-manager
      version: "{{ kafka_manager_version }}"

- name: install manager 
  include_role:
    name: install
  vars:
    opts:
      pkg_name: "kafka-manager"
      pkg_version: "{{ kafka_manager_version }}"
      pkg_type: zip
      pkg_url: "https://github.com/yahoo/CMAK/archive/{{ kafka_manager_version }}.zip"
      extracts: yes
      dest_path: "~/.ansible/cache/kafka-manager/"
      creates: "~/.ansible/cache/kafka-manager/kafka-manager-{{ kafka_manager_version }}/sbt"
      bin_path:


- name: build kafka manager
  shell: ./sbt dist
  args:
    chdir: "~/.ansible/cache/kafka-manager/CMAK-{{ kafka_manager_version }}/"
    executable: /bin/bash
  delegate_to: localhost


  #- name: move CMAK files
  # copy:
  # src: ~/.ansible/cache/kafka-manager/CMAK-{{ kafka_manager_version }}/
  # dest: /root/.ansible/cache/kafka-manager/kafka-manager-{{ kafka_manager_version }}
  # mode: "0755"

- name: copy bulit manager
  copy:
    src: ~/.ansible/cache/kafka-manager/CMAK-{{ kafka_manager_version }}/target/universal/cmak-{{ kafka_manager_version }}.zip
    dest: /tmp/kafka-manager-{{ kafka_manager_version }}.zip
    owner: kafka
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=
 
- name: install kafka manager binaries
  unarchive:
    src: /tmp/kafka-manager-{{ kafka_manager_version }}.zip
    dest: /opt/kafka-manager/
    owner: kafka
    group: kafka
    creates: /opt/kafka-manager/{{ kafka_manager_version }}/bin/kafka-manager
    remote_src: yes

- name: move CMAK files
  copy:
    src: /opt/kafka-manager/cmak-{{ kafka_manager_version }}/
    dest: /opt/kafka-manager/{{ kafka_manager_version }}
    mode: "0755"
    remote_src: yes

- name: create symbolic links
  file:
    src: /opt/{{ item.name }}/{{ item.version }}/bin/cmak
    dest: /opt/{{ item.name }}/{{ item.version }}/bin/kafka-manager
    owner: kafka
    group: kafka
    state: link
  with_items:
    - name: kafka-manager
      version: "{{ kafka_manager_version }}"


- name: update permissions of service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    recurse: yes
    state: directory
  with_items:
    - kafka-manager

