---
- name: set variables
  set_fact:
    kafka_version: 3.1.0   #实际安装版本
    scala_versions:
    - 2.13

- name: install confd files
  include_role:
    name: confd-files

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - kafka
  loop_control:
    loop_var: svc_name

- name: add the service group
  group:
    name: kafka
    state: present

- name: add the service user
  user:
    name: kafka
    groups: kafka
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

- name: install tools
  apt:
    update_cache: yes
    name: ['openjdk-11-jdk','unzip','arping']
    state: present

- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install kafka
  include_role:
    name: install
  vars:
    opts:
      pkg_name: kafka
      pkg_version: "{{ item }}-{{ kafka_version }}"
      pkg_type: tgz
      pkg_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ item }}-{{ kafka_version }}.tgz"
      extracts: yes
      creates: "bin/kafka-server-start.sh"
      target_owner: kafka
      target_group: kafka
      bin_path:
  with_items: "{{ scala_versions }}"

- name: install statsd metrics
  copy:
    src: ../deps/kafka-statsd-metrics2-master-0.4.0.jar
    dest: /opt/kafka/{{ item }}-{{ kafka_version }}/libs
    owner: kafka
    group: kafka
  with_items: "{{ scala_versions }}"

- name: set up version env
  copy:
    dest: /opt/app/bin/envs/version.env
    content: |
      KAFKA_VERSION_4_MANAGER=3.1.0      #因为 cmak 只支持到3.2.0
      KAFKA_VERSION={{ kafka_version }}

