---
- name: set variables
  set_fact:
    kafka_version: 2.6.1   #实际安装版本
    scala_versions:
      - 2.13
      - 2.12

- name: prepare service user
  include_role:
    name: create-service-user-1.0.0
  vars:
    svc_user: kafka
    svc_group: svc

- name: install confd files
  include_role:
    name: confd-files-1.0.9

- name: install tools
  apt:
    update_cache: yes
    name: ['default-jdk','unzip']
    state: present

- name: copy binaries
  copy:
    src: "{{ role_path }}/files/opt/app/"
    dest: /opt/app/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: install kafka
  include_role:
    name: install-1.0.5
  vars:
    opts:
      pkg_name: kafka
      pkg_version: "{{ item }}-{{ kafka_version }}"
      pkg_type: tgz
      pkg_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ item }}-{{ kafka_version }}.tgz"
      extracts: yes
      creates: "bin/kafka-server-start.sh"
      target_owner: kafka
      target_group: svc
      bin_path:
  with_items: "{{ scala_versions }}"

- name: install statsd metrics
  copy:
    src: ../deps/kafka-statsd-metrics2-master-0.4.0.jar
    dest: /opt/kafka/{{ item }}-{{ kafka_version }}/libs
    owner: kafka
    group: svc
  with_items: "{{ scala_versions }}"

- name: set up version env
  copy:
    dest: /opt/app/current/bin/envs/version.env
    content: |
      KAFKA_VERSION_4_MANAGER=2.2.0      #因为 cmak 支持的kafka版本为2.2.0 2.4.0，无 2.3.0， 实测2.3.0也可使用
      KAFKA_VERSION={{ kafka_version }}

