---
- name: set variables
  set_fact:
    kafka_version: "{{ kafka_version | d('3.8.1') }}"
    scala_version: "{{ scala_version | d('2.13') }}"
    installPath: "/opt/kafka"

- name: install confd files
  include_role:
    name: confd-files

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - kafka
  loop_control:
    loop_var: svc_name

- name: add the service group
  group:
    name: kafka
    state: present

- name: add the service user
  user:
    name: kafka
    groups: kafka
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: kafka
      pkg_version: "{{ scala_version }}-{{ kafka_version }}"
      pkg_feature: "linux"
      pkg_fileType: ".tgz"
      pkg_url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

- name: prepare dir
  file:
    path: "{{ installPath }}/{{ scala_version }}-{{ kafka_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ installPath }}/{{ scala_version }}-{{ kafka_version }}"
    dest: "{{ installPath }}/current"
    state: link

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}/{{ scala_version }}-{{ kafka_version }}"
    creates: "{{ installPath }}/{{ scala_version }}-{{ kafka_version }}/bin/kafka-server-start.sh"
    extra_opts:
    - --strip-components=1

- name: set up version env
  copy:
    dest: /opt/app/bin/envs/version.env
    content: |
      KAFKA_VERSION_4_MANAGER=3.1.0      #因为 cmak 只支持到3.2.0
      KAFKA_VERSION={{ kafka_version }}

