---
- name: set variables
  set_fact:
    kafka_version: 2.3.0   #实际安装版本
    scala_version: "2.11"

- name: copy systemd files
  copy: #拷贝service文件
    src: files/{{ item }}
    dest: /{{ item }}
    directory_mode: yes
  with_items:
    - lib/systemd/system/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - kafka
  loop_control:
    loop_var: svc_name

- name: add the service group
  group:
    name: kafka
    state: present

- name: add the service user
  user:
    name: kafka
    groups: kafka
    shell: /sbin/nologin
    create_home: no
    home: "/opt/kafka/current"
    append: yes
    comment: "Service User"
    state: present


- name: copy binaries
  copy: #拷贝service文件
    src: files/opt/
    dest: /opt
    owner: root
    group: kafka
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: prepare service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    state: directory
  with_items:
    - kafka/{{ kafka_version }}

- name: create symbolic links
  file:
    src: /opt/{{ item.name }}/{{ item.version }}
    dest: /opt/{{ item.name }}/current
    owner: kafka
    group: kafka
    state: link
  with_items:
    - name: kafka
      version: "{{ kafka_version }}"

- name: download Kafka
  get_url:
    url: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: files/tmp/kafka-{{ kafka_version }}.tgz
  delegate_to: localhost

- name: install kafka
  unarchive:
    src: files/tmp/kafka-{{ kafka_version }}.tgz
    dest: /opt/kafka/{{ kafka_version }}
    owner: kafka
    group: kafka
    creates: /opt/kafka/{{ kafka_version }}/bin/kafka-server-start.sh
    extra_opts: [ '--strip-components=1' ]

- name: install statsd metrics
  copy:
    src: ../deps/kafka-statsd-metrics2-master-0.4.0.jar
    dest: /opt/kafka/current/libs
    owner: kafka
    group: kafka

- name: update permissions of service directories
  file:
    path: /opt/{{ item }}
    owner: kafka
    group: kafka
    recurse: yes
    state: directory
  with_items:
    - kafka

- name: add Kafka commands to system-wide $PATH
  copy:
    dest: /etc/profile.d/kafka-path.sh
    content: 'PATH=$PATH:/opt/kafka/current/bin'

- name: set up version env
  copy:
    dest: /opt/app/bin/version.env
    content: KAFKA_VERSION=2.2.0      #因为kafka manager支持的最大的kafka版本为2.2.0，实测2.3.0也可使用

- name: install confd files
  include_tasks: ../../utils/tasks/process-confd-files.yml
