[template]
src = "zabbix-agent.sh.tmpl"
dest = "/opt/app/current/bin/tmpl/zabbix-agent.sh"
mode = "0700"
keys = [
  "/",
]
reload_cmd = "/opt/app/current/bin/tmpl/zabbix-agent.sh; appctl reload zabbix-agent"