---
- name: common setup
  hosts: all
  strategy: free
  vars:
    target_env: "{{ lookup('env', 'target') }}"
    local_cache_path: "~/.ansible/cache"
  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - disable-apt-jobs
    - disable-motd
    - app-agent
    - appctl
    - arping
    - caddy
    - kafka
    - kafka-manager
    - zabbix-agent
    loop_control:
      loop_var: service_name
