---
- name: common setup
  hosts: all
  strategy: free
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ service_name }}"
    loop:
    - tar
    - nc
    - os-update
    - disable-package-manager-timers
    - disable-motd
    - app-agent
    - appctl
    - arping
    - openjdk
    - caddy
    - kafka
    - unzip
    - kafka-ui
    - zabbix-agent
    - jmx-exporter
    - users_groups
    - crashkernel
    - pwquality
    loop_control:
      loop_var: service_name
