---
- name: set variables
  set_fact:
    appAgentVersion: v1.0.6

- name: Prepare directories
  file:
    path: "/tmp/app-agent"
    state: directory

- name: Download reusable binaries locally
  get_url:
    url: "https://github.com/QingCloudAppcenter/AppcenterAgent/releases/download/{{ appAgentVersion }}/app-agent-linux-amd64.tar.gz"
    dest: "/tmp/app-agent-linux-amd64.tar.gz"
  delegate_to: localhost

- name: Extract binary
  unarchive:
    src: "/tmp/app-agent-linux-amd64.tar.gz"
    dest: "/tmp/app-agent"
    creates: "/tmp/app-agent/bin"
    extra_opts: [ --strip-components=1 ]

- name: Create symbolic Link
  shell: ./install.sh
  args:
    chdir: /tmp/app-agent/

- name: Copy confd toml files
  copy:
    src: "./files/etc/confd/conf.d/{{ item }}.sh.toml"
    dest: "/etc/confd/conf.d/{{ item }}.sh.toml"
    owner: root
    group: root
    directory_mode: yes
    mode: 755
  with_items:
        - make_zabbix
        - make

- name: Compile tmpl files
  shell: |
    srcDir="./files/etc/confd/templates"
    srcFiles="$(ls $srcDir/*.tmpl)"
    destDir="files/tmp/confd/templates"
    rm -rf $destDir
    mkdir -p $destDir
    for tmpl in $srcFiles; do
      if [[ "$tmpl" =~ ^3 ]]; then
        cat $tmpl >> $destDir/make_zabbix.sh.tmpl
        echo >> $destDir/make_zabbix.sh.tmpl
      else
        cat $tmpl >> $destDir/make.sh.tmpl
        echo >> $destDir/make.sh.tmpl
      fi 
    done
  args:
    executable: /bin/bash
  delegate_to: localhost

- name: Copy confd tmpl files
  copy:
    src: files/tmp/confd/templates/{{ item }}.sh.tmpl
    dest: /etc/confd/templates/{{ item }}.sh.tmpl
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  with_items:
      - make
      - make_zabbix
