---
- name: Copy confd toml files
  copy:
    src: "files/etc/confd/conf.d/make.sh.toml"
    dest: /etc/confd/conf.d/make.sh.toml
    owner: root
    group: root

- name: Compile tmpl files
  shell: |
    srcDir="files/etc/confd/templates"
    srcFiles="$(ls $srcDir/*.tmpl)"
    destDir="files/tmp/confd/templates"
    rm -rf $destDir
    mkdir -p $destDir
    tmplFile=$destDir/make.sh.tmpl
    for tmpl in $srcFiles; do
      cat $tmpl >> $tmplFile
      echo >> $tmplFile
    done
  args:
    executable: /bin/bash
  delegate_to: localhost

- name: Copy confd tmpl files
  copy:
    src: files/tmp/confd/templates/make.sh.tmpl
    dest: /etc/confd/templates/make.sh.tmpl
    owner: root
    group: root
