[template]
src = "kafka-manager.sh.tmpl"
dest = "/opt/app/bin/tmpl/kafka-manager.sh"
mode = "0600"
keys = [
  "/",
]
reload_cmd = "/opt/app/bin/tmpl/kafka-manager.sh; /opt/app/bin/ctl.sh update kafka-manager; appctl clusterAct update"