---
- name: set variables
  set_fact:
    zabbix_version: "{{ zabbix_version | d('7.2') }}"
    os: "{{ os | d(default_os) }}"

- name: install confd files
  include_role:
    name: confd-files

- name: add the service group
  group:
    name: zabbix
    state: present

- name: add the service user
  user:
    name: zabbix
    groups: zabbix
    shell: /bin/false
    create_home: no
    home: "/var/lib/zabbix/"
    append: yes
    comment: "Service User"
    state: present

- name: prepare service directories
  file:
    path: /opt/{{ item }}
    owner: zabbix
    group: zabbix
    state: directory
  with_items:
    - zabbix

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: zabbix-agent
      pkg_version: "{{ zabbix_version }}"
      pkg_feature: "linux"
      pkg_fileType: ".deb"
      pkg_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ osv }}_all.deb"
  when: os == 'ubuntu'

- name: set centos version
  set_fact:
    centos_version: '8'
  when: os == 'kylin'

- name: set centos version
  set_fact:
    centos_version: '9'
  when: os == 'openEuler'

- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: zabbix-agent
      pkg_version: "{{ zabbix_version }}"
      pkg_feature: "linux"
      pkg_fileType: ".rpm"
      pkg_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/centos/{{ centos_version }}/noarch/zabbix-release-latest-{{ zabbix_version }}.el{{ centos_version }}.noarch.rpm"
  when: os == 'kylin' or os == 'openEuler'

- name: copy file
  copy:
    src: "{{ downloaded }}"
    dest: "/tmp"

- name: ubuntu block
  block:
  - name: install repo - ubuntu
    apt:
      deb: "/tmp/{{ downloaded | basename }}"
      policy_rc_d: 101
      state: present
  - name: install agent - ubuntu
    apt:
      name: zabbix-agent
      state: present
  when: os == 'ubuntu'

- name: kylin/openEuler block
  block:
  - name: install repo
    dnf:
      name: "/tmp/{{ downloaded | basename }}"
      disable_gpg_check: true
      state: present
  - name: install agent
    dnf:
      name: zabbix-agent
      state: present
  when: os == 'kylin' or os == 'openEuler'

- name: mask service
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - zabbix-agent
  loop_control:
    loop_var: svc_name

- name: fix logrotate config
  lineinfile:
    path: /etc/logrotate.d/zabbix-agent
    regexp: '^/.*/zabbix_agentd.log {'
    line: '/data/log/zabbix/zabbix_agentd.log {'
    state: present

