---
- name: set variables
  set_fact:
    zabbix: "3.4"

- name: install confd files
  include_role:
    name: confd-files-1.0.2

- name: add the service group
  group:
    name: zabbix
    state: present

- name: add the service user
  user:
    name: zabbix
    groups: zabbix
    shell: /bin/false
    create_home: no
    home: "/var/lib/zabbix/"
    append: yes
    comment: "Service User"
    state: present

- name: prepare service directories
  file:
    path: /opt/{{ item }}
    owner: zabbix
    group: zabbix
    state: directory
  with_items:
    - zabbix

- name: download zabbix deb
  unarchive:
    src: https://repo.zabbix.com/zabbix/{{ zabbix }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix }}-1+xenial_all.deb
    dest: /opt/zabbix
    creates: /opt/zabbix/
    remote_src: yes

- name: install zabbix agent
  shell: |
    dpkg -i zabbix-release_{{ zabbix }}-1+xenial_all.deb
    apt update 
    apt -y install zabbix-agent
  args:
    chdir: /opt/zabbix/
    executable: /bin/bash
    creates: /etc/zabbix/

- name: disable auto start
  systemd:
    name: "{{ svc_name }}"
    state: stopped
    masked: yes
  loop:
  - zabbix-agent
  loop_control:
    loop_var: svc_name

